import logging
import os
import chromadb
import pandas as pd
from sentence_transformers import SentenceTransformer

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("VectorIndexer")


def load_pyspark_output(parquet_dir: str) -> pd.DataFrame:
    """Loads the standardized parquet metadata generated by PySpark."""
    logger.info(f"Loading PySpark processed metadata from {parquet_dir}...")
    if not os.path.exists(parquet_dir):
        raise FileNotFoundError(
            f"Directory {parquet_dir} not found. Please run the PySpark script first."
        )
    # pandas can read a directory of parquet files natively
    return pd.read_parquet(parquet_dir)


def initialize_vector_store(db_path: str, collection_name: str):
    """Initializes a persistent local ChromaDB client and collection."""
    logger.info(f"Initializing persistent ChromaDB at: {db_path}")
    client = chromadb.PersistentClient(path=db_path)

    # Create or fetch the collection
    collection = client.get_or_create_collection(name=collection_name)
    return collection


def index_metadata():
    # Paths matches the output from our PySpark step
    parquet_dir = "data/processed_metadata_atlas"
    chroma_db_path = "data/chroma_db"
    collection_name = "global_health_metadata"

    # 1. Load Data
    df = load_pyspark_output(parquet_dir)

    # 2. Initialize Hugging Face Embedding Model
    logger.info("Loading Hugging Face model (all-MiniLM-L6-v2)...")
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

    # 3. Initialize Vector DB
    collection = initialize_vector_store(chroma_db_path, collection_name)

    logger.info(f"Beginning embedding generation for {len(df)} records...")

    # Prepare lists for ChromaDB batch insertion
    ids = []
    documents = []
    embeddings = []
    metadatas = []

    for idx, row in df.iterrows():
        # Unique identifier for the vector record
        unique_id = f"{row['source_dataset']}_{row['table_id']}_{row['variable_id']}"

        # Construct metadata dictionary for filtering later
        metadata = {
            "source_dataset": str(row["source_dataset"]),
            "table_id": str(row["table_id"]),
            "variable_id": str(row["variable_id"]),
            "variable_name": str(row["variable_name"]),
            "description": str(row["description"]),
        }

        # Generate embedding for the composite text
        # (In production, you would batch encode, but for metadata schemas this is highly readable)
        embedding = model.encode(row["composite_text"]).tolist()

        ids.append(unique_id)
        documents.append(row["composite_text"])
        embeddings.append(embedding)
        metadatas.append(metadata)

    # 4. Upsert into ChromaDB
    logger.info(f"Upserting vectors into ChromaDB collection '{collection_name}'...")
    collection.upsert(
        ids=ids, documents=documents, embeddings=embeddings, metadatas=metadatas
    )

    logger.info("Successfully built semantic vector database!")

    # --- QUICK SMOKE TEST ---
    logger.info("Running a quick semantic search test...")
    test_query = "body mass index metrics"
    query_vector = model.encode(test_query).tolist()

    results = collection.query(query_embeddings=[query_vector], n_results=2)

    print("\n🔍 --- SEMANTIC SEARCH TEST RESULTS ---")
    for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
        print(f"Source: {meta['source_dataset']} | Variable: {meta['variable_id']}")
        print(f"Description: {meta['description']}")
        print("-" * 40)


if __name__ == "__main__":
    index_metadata()
